
spring:
  servlet:
    multipart: # 限制图片上传的大小
      max-file-size: 100MB
      max-request-size: 1024MB
  http:
    encoding:
      charset: UTF-8
  redis:
    hostName: 127.0.0.1
    port: 6379
#    password: xxxxxxxxx
    jedis:
      pool:
        maxTotal: 50         # 最大连接数
        maxIdle: 10          # 最大空闲连接数
        minIdle: 5           # 最小空闲连接数
        maxWaitMillis: 1000  # 最大超时毫秒
        
server:
  servlet:
    context-path: /job-two/
  port: 8081 # 8080 8081 本地启动的机器是哪个端口大cpu先执行哪个
  
log:
  level: info
  path: /logs/job-two/job-two.log # 最前面加/为绝对路径
    
jasypt:
  encryptor:
    bean: encryptorBean
    